<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mzn</string>
		<string>dzn</string>
	</array>
	<key>name</key>
	<string>Minizinc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.language.mzn</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name = 'constant.character.escape.mzn'; match = '\\.';</key>
					<false/>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\%.*</string>
			<key>name</key>
			<string>comment.line.percentage.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>%(\\"|[^"])*(?="|$\n?)</string>
			<key>name</key>
			<string>comment.line.percentage</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
			<key>name</key>
			<string>constant.numeric.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*(\+|\-|\&lt;\-\&gt;|\&lt;|\&gt;|\/\\|\/|\\\/|\||=|\!=|\.\.|\+\+|\*)\s*</string>
			<key>name</key>
			<string>keyword.operator.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(diff|symdiff|union|superset|subset|xor|not|intersect|div|mod)\b</string>
			<key>name</key>
			<string>keyword.language.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ann|annotation|any|array|assert|bool|constraint|enum|float|function|in|include|int|list|of|op|output|minimize|maximize|par|predicate|record|set|solve|string|test|tuple|type|var|where)\b</string>
			<key>name</key>
			<string>keyword.language.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(abort|count|table|abs|acosh|array_intersect|array_union|array1d|array2d|array3d|array4d|array5d|array6d|asin|assert|atan|bool2int|card|ceil|concat|cos|cosh|dom|dom_array|dom_size|fix|exp|floor|index_set|index_set_1of2|index_set_2of2|index_set_1of3|index_set_2of3|index_set_3of3|int2float|is_fixed|join|lb|lb_array|length|ln|log|log2|log10|min|max|pow|product|round|set2array|show|show_int|show_float|sin|sinh|sqrt|sum|tan|tanh|trace|ub|ub_array)(?=\s*\()</string>
			<key>name</key>
			<string>support.function.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|then|else|endif|false|true)\b</string>
			<key>name</key>
			<string>keyword.controll.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(satisfy|maximize|minimize|let|exists)\b</string>
			<key>name</key>
			<string>keyword.language.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(forall|set_search|partition_set)(?=\s*\()</string>
			<key>name</key>
			<string>support.function.mzn</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mzn</string>
	<key>uuid</key>
	<string>1e47a6c9-24f4-416d-b5af-db02312df3e4</string>
</dict>
</plist>
